### PR TITLE
2023-10

### PR DESCRIPTION
**Pull request by liyuweiying**

### CODE REVIEW

**Comment by liyuweiying** [comment]
Done. Btw small question here: should split season be put in new or old? (like Dr. Stone this season)

**Comment by FlandreDaisuki** [comment]
In DMHY site, it is hard to recognize an anime episode whether it is a split season.
currently, LGTM.

Additionally optional request, can you add "黑暗集會" to `docs/history/2023-07/new.yaml` & `docs/old.yaml`?

**Comment by liyuweiying** [comment]
Done. Dark Gathering is added.

**Comment by FlandreDaisuki** [comment]
Perfect! Thank you <3

I prefer merge your PR by squash. If you feel fine, give me ❤️ on this response.
Otherwise, give me 😕 and I'll merge the PR with a merge commit.

**Pull request merged**
